---
# main rule for Cisco ASA

# "ansible_facts": {
#         "_excel": [
#             {
#                 "dest": {
#                     "adresses": [
#                         {
#                             "ipv4": "7.7.7.1",
#                             "name": "pub_host_A"
#                         },
#                         {
#                             "ipv4": "7.7.7.2",
#                             "name": "pub_host_B"
#                         }
#                     ],
#                     "zone": "port3"
#                 },
#                 "name": "rule_C",
#                 "rules": {
#                     "action": "permit",
#                     "ips_sensor": "default",
#                     "logging_close": true,
#                     "logging_init": false
#                 },
#                 "services": [
#                     "http",
#                     "https"
#                 ],
#                 "src": {
#                     "adresses": [
#                         {
#                             "ipv4": "10.10.2.3",
#                             "name": "inside_host_D"
#                         }
#                     ],
#                     "zone": "port2"
#                 }
#             },
#             {
#                 "dest": {
#                     "adresses": [
#                         {
#                             "ipv4": "7.7.7.2",
#                             "name": "pub_host_B"
#                         }
#                     ],
#                     "zone": "port3"
#                 },
#                 "name": "rule_B",
#                 "rules": {
#                     "action": "permit",
#                     "ips_sensor": "default",
#                     "logging_close": true,
#                     "logging_init": false
#                 },
#                 "services": [
#                     "https"
#                 ],
#                 "src": {
#                     "adresses": [
#                         {
#                             "ipv4": "10.10.2.3",
#                             "name": "inside_host_D"
#                         },
#                         {
#                             "ipv4": "10.10.2.2",
#                             "name": "inside_host_C"
#                         }
#                     ],
#                     "zone": "port2"
#                 }
#             }
#         ]
#     },
#     "changed": false
# }

- name: include 
  include_vars: vars/asa_services.yml
  tags: [rule]

- name: start loop for rules
  include_tasks:
    file: rule_loop.yml
    apply:
      tags: rule
  loop: "{{ fw_rules }}"
  loop_control:
    label: "{{ _rule.name }}"
    loop_var: _rule
  when: fw_rules | length > 0 
  tags: [rule]