---

- name: gather facts from FortiGate
  fortinet.fortios.fortios_configuration_fact: 
    vdom: "{{ fw_fg_vdom | default('') }}"
    selectors:
      - selector: system_interface
  register: _fg_facts

- debug:
    var: _fg_facts
