---
# inner rule
# Fortigate

- set_fact:
    _src_ips: []
    _dest_ips: []
    _services: []
    _action: "{{ 'accept' if _rule.rule.action == 'permit' else 'deny' }}"

- name: loop src IP address list
  include_tasks:
    file: iprange_loop.yml
    apply:
      tags: rule
  loop: "{{ _rule.src.addresses }}"
  loop_control:
    label: "{{ _src_address.ipv4 }}"
    loop_var: _src_address
  when: _rule.src.addresses | length > 0
  tags: [rule]
  

- name: generate list of source addresses
  set_fact: 
    _src_ips: "{{ _src_ips + [item.ipv4] }}"
  loop: "{{ _rule.src.addresses }}"
  loop_control:
    label: "{{ item.name }}"

- name: generate list of destination addresses
  set_fact: 
    _dest_ips: "{{ _dest_ips + [item.ipv4] }}"
  loop: "{{ _rule.dest.addresses }}"
  loop_control:
    label: "{{ item.name }}"

- name: generate list of services
  set_fact: 
    _services: "{{ _services + [panos_services[item]] }}"
  loop: "{{ _rule.services }}"

- debug: 
    var:  _services

- name: "add rule {{ _rule.name }} to PanOS"
  fortinet.fortios.fortios_firewall_policy:
    description: "{{ _rule.description | default(omit) }}"
    source_zone: "{{ _rule.src.zone }}"
    destination_zone: "{{ _rule.dest.zone }}"
    service: "{{ _services }}"
    firewall_policy: 
      name: "{{ _rule.name }}" 
      dstaddr:
        name: "{{ _dstaddrs }}"
      service: 
        name: "{{ _services }}"
      action: "{{ _action }}" 
    commit: "False"
